const { chromium } = require('@playwright/test');
const http = require('http');
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const repo = path.resolve(__dirname,'..');
const root = path.join(repo,'data/web');
const artifacts = path.join(repo,'artifacts');
fs.mkdirSync(artifacts,{recursive:true});
const server = http.createServer((req,res) => {
  const p = path.join(root,req.url==='/'||req.url==='/update'?'index.html':req.url);
  if (!fs.existsSync(p)) {res.writeHead(404);res.end();return;}
  res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html; charset=utf-8');
  res.end(fs.readFileSync(p));
});
(async()=>{
await new Promise(resolve=>server.listen(18472,'127.0.0.1',resolve));
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1150,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
let settings={wifiSSID:'测试网络',wifiPass:'***',agServer:'http://192.168.1.1:8045',agToken:'***',agModelLabel:'测试模型',refreshMin:5,channelSec:8,galleryRefreshSec:10,brightness:80,tzMinutes:480,selectedPage:0,showHome:true,showAntigravity:true,showInfo:true,showGallery:true,autoRotate:true,agWeeklyHero:false,invertDisplay:true};
const cp = require('child_process'), os = require('os');
const runner = path.join(os.tmpdir(),'glimmer-gallery-test');
cp.execFileSync('g++',['-std=c++17','-O2','-Isrc/gallery','src/gallery/gallery.cpp','tests/gallery_runner.cpp','-o',runner],{cwd:repo});
const frame = JSON.parse(cp.execFileSync(runner,['20261008']));
const saves=[];
await page.route('**/api/**',async route=>{
const req=route.request(),url=new URL(req.url()).pathname;
let reply={ok:true};
if(url==='/api/settings'&&req.method()==='GET') reply=settings;
if(url==='/api/settings'&&req.method()==='POST'){const b=req.postDataJSON();saves.push(b);settings={...settings,...b};}
if(url==='/api/state')reply={fw:'0.21.0-cn-gallery',wifi:'connected',ip:'192.168.1.88',ssid:'测试网络',rssi:-54,uptime_s:7380,heap:32500,channel:'Gallery',gallery_seed:frame.seed};
if(url==='/api/gallery')reply=frame;
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(reply)});
});
await page.goto('http://127.0.0.1:18472');
await page.waitForFunction(()=>document.getElementById('preview-hint').textContent==='设备当前画廊画面');
assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');
assert.equal(await page.locator('#wifi-state').textContent(),'已连接');
const bodyText=await page.locator('body').innerText();
assert(!/Status|Settings|Weather|Push|Tokens|Save|Refresh/.test(bodyText));
await page.screenshot({path:artifacts+'/control-panel-desktop.png',fullPage:true});
await page.getByRole('button',{name:'屏幕设置',exact:true}).click();
await page.locator('[name="autoRotate"]').uncheck();
await page.locator('[name="showGallery"]').uncheck();
await page.locator('[name="selectedPage"]').selectOption('3');
await page.locator('[name="galleryRefreshSec"]').fill('17');
await page.locator('[name="tzMinutes"]').fill('0');
await page.getByRole('button',{name:'保存屏幕设置',exact:true}).click();
await page.waitForFunction(()=>!document.getElementById('notice').hidden);
await page.waitForTimeout(150);
assert.equal(saves[0].galleryRefreshSec,17);
assert.equal(saves[0].showGallery,true);
assert.equal(saves[0].selectedPage,3);
assert.equal(saves[0].tzMinutes,0);
assert.equal(saves[0].autoRotate,false);
assert.equal(saves[0]._restart,false);
assert(!('wifiPass' in saves[0]));
await page.screenshot({path:artifacts+'/control-panel-settings.png',fullPage:true});
await page.getByRole('button',{name:'网络与额度',exact:true}).click();
await page.locator('[name="refreshMin"]').fill('7');
await page.getByRole('button',{name:'保存额度设置',exact:true}).click();
await page.waitForTimeout(150);
assert.equal(saves[1].refreshMin,7);
assert.equal(saves[1].agToken,'***');
assert(!('wifiSSID' in saves[1]));
await page.getByRole('button',{name:'保存并重启',exact:true}).click();
await page.waitForTimeout(150);
assert.equal(saves[2]._restart,true);
await page.goto('http://127.0.0.1:18472/update');
await page.waitForFunction(()=>!document.getElementById('maintenance').hidden);
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'设备状态',exact:true}).click();
await page.screenshot({path:artifacts+'/control-panel-mobile.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);
console.log(JSON.stringify({checks:['中文页面与四页导航','ESP 实际画面描述预览','画廊间隔持久化请求','固定画廊自动启用','UTC 零偏移','凭据掩码保留','额度和无线网络分别保存','刷写入口中文','手机无横向溢出'],browserErrors:errors},null,2));
await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1);});
